version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

#define workflow
workflows:
  version: 2
  workflow:
    jobs:
      - build
